<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NODLTP52066174" ignored="2" name="EmployeesRestAPITest" tests="30" failures="14" timestamp="2020-10-07T13:23:30 IST" time="19.991" errors="0">
  <testcase name="checkdata" time="0.005" classname="Employeetestcasepackage.reqres"/>
  <testcase name="printheader" time="0.001" classname="Employeetestcasepackage.reqres"/>
  <testcase name="checkContentLenght" time="0.001" classname="Employeetestcasepackage.TC001_GetAllDataEmployee"/>
  <testcase name="checkContentType" time="0.002" classname="Employeetestcasepackage.TC001_GetAllDataEmployee"/>
  <testcase name="checkCookies" time="0.001" classname="Employeetestcasepackage.TC001_GetAllDataEmployee"/>
  <testcase name="checkResponseTime" time="0.002" classname="Employeetestcasepackage.TC001_GetAllDataEmployee"/>
  <testcase name="checkResposeBody" time="0.003" classname="Employeetestcasepackage.TC001_GetAllDataEmployee"/>
  <testcase name="checkStatusCode" time="0.001" classname="Employeetestcasepackage.TC001_GetAllDataEmployee"/>
  <testcase name="checkcontentEncoding" time="0.002" classname="Employeetestcasepackage.TC001_GetAllDataEmployee"/>
  <testcase name="checkserverType" time="0.002" classname="Employeetestcasepackage.TC001_GetAllDataEmployee">
    <failure type="java.lang.AssertionError" message="expected [nginx/1.14.1] but found [nginx/1.16.0]">
      <![CDATA[java.lang.AssertionError: expected [nginx/1.14.1] but found [nginx/1.16.0]
at Employeetestcasepackage.TC001_GetAllDataEmployee.checkserverType(TC001_GetAllDataEmployee.java:96)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkserverType -->
  <testcase name="checkstatusLine" time="0.001" classname="Employeetestcasepackage.TC001_GetAllDataEmployee"/>
  <testcase name="checkContentLenght" time="0.001" classname="Employeetestcasepackage.TC002_Get_SingleData_employee">
    <failure type="java.lang.NumberFormatException" message="null">
      <![CDATA[java.lang.NumberFormatException: null
at java.lang.Integer.parseInt(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at Employeetestcasepackage.TC002_Get_SingleData_employee.checkContentLenght(TC002_Get_SingleData_employee.java:75)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkContentLenght -->
  <testcase name="checkContentType" time="0.001" classname="Employeetestcasepackage.TC002_Get_SingleData_employee">
    <failure type="java.lang.AssertionError" message="expected [application/json;charset=utf-8] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json;charset=utf-8] but found [text/html; charset=UTF-8]
at Employeetestcasepackage.TC002_Get_SingleData_employee.checkContentType(TC002_Get_SingleData_employee.java:61)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResponseTime" time="0.001" classname="Employeetestcasepackage.TC002_Get_SingleData_employee"/>
  <testcase name="checkResposeBody" time="0.003" classname="Employeetestcasepackage.TC002_Get_SingleData_employee"/>
  <testcase name="checkStatusCode" time="0.001" classname="Employeetestcasepackage.TC002_Get_SingleData_employee">
    <failure type="java.lang.AssertionError" message="expected [400] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [429]
at Employeetestcasepackage.TC002_Get_SingleData_employee.checkStatusCode(TC002_Get_SingleData_employee.java:38)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkserverType" time="0.001" classname="Employeetestcasepackage.TC002_Get_SingleData_employee">
    <failure type="java.lang.AssertionError" message="expected [nginx/1.14.1] but found [nginx/1.16.0]">
      <![CDATA[java.lang.AssertionError: expected [nginx/1.14.1] but found [nginx/1.16.0]
at Employeetestcasepackage.TC002_Get_SingleData_employee.checkserverType(TC002_Get_SingleData_employee.java:68)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkserverType -->
  <testcase name="checkstatusLine" time="0.001" classname="Employeetestcasepackage.TC002_Get_SingleData_employee">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at Employeetestcasepackage.TC002_Get_SingleData_employee.checkstatusLine(TC002_Get_SingleData_employee.java:53)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase name="checkContentType" time="0.001" classname="Employeetestcasepackage.TC003_PostEmpData">
    <failure type="java.lang.AssertionError" message="expected [application/json;charset=utf-8] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json;charset=utf-8] but found [text/html; charset=UTF-8]
at Employeetestcasepackage.TC003_PostEmpData.checkContentType(TC003_PostEmpData.java:81)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResposeBody" time="0.003" classname="Employeetestcasepackage.TC003_PostEmpData">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Employeetestcasepackage.TC003_PostEmpData.checkResposeBody(TC003_PostEmpData.java:57)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkResposeBody -->
  <testcase name="checkStatusCode" time="0.001" classname="Employeetestcasepackage.TC003_PostEmpData">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at Employeetestcasepackage.TC003_PostEmpData.checkStatusCode(TC003_PostEmpData.java:66)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkcontentEncoding" time="0.001" classname="Employeetestcasepackage.TC003_PostEmpData"/>
  <testcase name="checkserverType" time="0.0" classname="Employeetestcasepackage.TC003_PostEmpData"/>
  <testcase name="checkstatusLine" time="0.001" classname="Employeetestcasepackage.TC003_PostEmpData">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at Employeetestcasepackage.TC003_PostEmpData.checkstatusLine(TC003_PostEmpData.java:73)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase name="checkContentType" time="0.0" classname="Employeetestcasepackage.TC005_Delete">
    <failure type="java.lang.AssertionError" message="expected [text/html; charset=UTF-8] but found [application/json]">
      <![CDATA[java.lang.AssertionError: expected [text/html; charset=UTF-8] but found [application/json]
at Employeetestcasepackage.TC005_Delete.checkContentType(TC005_Delete.java:61)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResposeBody" time="0.001" classname="Employeetestcasepackage.TC005_Delete">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Employeetestcasepackage.TC005_Delete.checkResposeBody(TC005_Delete.java:38)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkResposeBody -->
  <testcase name="checkStatusCode" time="0.001" classname="Employeetestcasepackage.TC005_Delete"/>
  <testcase name="checkcontentEncoding" time="0.0" classname="Employeetestcasepackage.TC005_Delete">
    <failure type="java.lang.AssertionError" message="expected [gzip] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [gzip] but found [null]
at Employeetestcasepackage.TC005_Delete.checkcontentEncoding(TC005_Delete.java:75)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkcontentEncoding -->
  <testcase name="checkserverType" time="0.001" classname="Employeetestcasepackage.TC005_Delete">
    <failure type="java.lang.AssertionError" message="expected [nginx/1.14.1] but found [nginx/1.16.0]">
      <![CDATA[java.lang.AssertionError: expected [nginx/1.14.1] but found [nginx/1.16.0]
at Employeetestcasepackage.TC005_Delete.checkserverType(TC005_Delete.java:68)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkserverType -->
  <testcase name="checkstatusLine" time="0.0" classname="Employeetestcasepackage.TC005_Delete"/>
  <testcase name="checktime" time="0.0" classname="Employeetestcasepackage.reqres">
    <ignored/>
  </testcase> <!-- checktime -->
  <testcase name="checkstatuscode" time="0.0" classname="Employeetestcasepackage.reqres">
    <ignored/>
  </testcase> <!-- checkstatuscode -->
</testsuite> <!-- EmployeesRestAPITest -->
